export interface NichePage {
  slug: string
  title: string
  metaTitle: string
  metaDescription: string
  h1: string
  subtitle: string
  keywords: string[]
  audience: string
  buttons: { icon: string; label: string }[]
  localBusiness?: {
    city: string
    regionCode: string
    lat?: number
    lon?: number
  }
}

export const NICHE_PAGES: NichePage[] = [
  {
    slug: 'kaspi-prodavets',
    title: 'Для продавцов Kaspi',
    metaTitle: 'Мобильная визитка для продавцов Kaspi — tapni.kz',
    metaDescription: 'Создайте страницу с Kaspi магазин, Kaspi Pay и WhatsApp для вашего Kaspi-магазина. Одна ссылка в шапке профиля Instagram или TikTok — клиенты сразу попадают в ваш магазин.',
    h1: 'Мобильная визитка для продавца Kaspi',
    subtitle: 'Продаёте на Kaspi? Ведёте Instagram или TikTok? Одна ссылка в bio с кнопкой прямо в ваш Kaspi магазин, Kaspi Pay и WhatsApp — покупатели из соцсетей попадают прямо к вашим товарам.',
    keywords: [
      'ссылка для kaspi магазина', 'визитка продавца kaspi', 'taplink для kaspi', 'kaspi продавец страница',
      'kaspi магазин instagram', 'kaspi продавец instagram', 'kaspi продавец tiktok',
      'kaspi продавец соцсети', 'ссылка kaspi магазин instagram bio', 'kaspi shop ссылка соцсети',
    ],
    audience: 'Продавцы Kaspi',
    buttons: [
      { icon: '🛒', label: 'Kaspi магазин' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '💬', label: 'WhatsApp' },
      { icon: '📍', label: '2ГИС — маршрут' },
    ],
  },
  {
    slug: 'instagram-bloger',
    title: 'Для Instagram блогеров',
    metaTitle: 'Ссылка в bio Instagram для блогеров Казахстана — tapni.kz',
    metaDescription: 'Лучший Taplink для Instagram-блогеров в Казахстане. Добавьте TikTok, Telegram-канал, YouTube и ссылку на донат в одно место.',
    h1: 'Ссылка в bio Instagram для блогеров',
    subtitle: 'Один адрес вместо 10 ссылок. Подписчики нажимают — попадают на ваш Telegram-канал, TikTok, YouTube и сотрудничество.',
    keywords: ['ссылка в bio instagram', 'taplink казахстан блогер', 'линк в инстаграм', 'bio link instagram казахстан'],
    audience: 'Блогеры и инфлюенсеры',
    buttons: [
      { icon: '📸', label: 'Instagram' },
      { icon: '🎵', label: 'TikTok' },
      { icon: '✈️', label: 'Telegram-канал' },
      { icon: '▶️', label: 'YouTube' },
    ],
  },
  {
    slug: 'kafe-restoran',
    title: 'Для кафе и ресторанов',
    metaTitle: 'Мобильная визитка для кафе и ресторана в Казахстане — tapni.kz',
    metaDescription: 'Создайте страницу для кафе с меню, 2ГИС, WhatsApp и Kaspi Pay. Клиенты видят расписание и могут сразу записаться или оплатить.',
    h1: 'Мобильная визитка для кафе и ресторана',
    subtitle: 'Меню, 2ГИС, WhatsApp-заказ, Kaspi Pay — всё в одной ссылке для Instagram. Клиент нажимает и сразу строит маршрут к вам.',
    keywords: ['мобильная визитка кафе казахстан', 'ссылка для ресторана instagram', 'меню кафе qr-код', 'taplink кафе'],
    audience: 'Кафе и рестораны',
    buttons: [
      { icon: '📋', label: 'Меню' },
      { icon: '📍', label: '2ГИС — найти нас' },
      { icon: '💬', label: 'WhatsApp заказ' },
      { icon: '💳', label: 'Kaspi Pay' },
    ],
  },
  {
    slug: 'master-uslugi',
    title: 'Для мастеров и услуг',
    metaTitle: 'Мобильная визитка для мастеров — маникюр, репетитор, мастер — tapni.kz',
    metaDescription: 'Создайте страницу для записи клиентов. Кнопка "Записаться", WhatsApp, 2ГИС и Kaspi Pay — клиент сам запишется и найдёт вас.',
    h1: 'Мобильная визитка для мастеров и частных услуг',
    subtitle: 'Кнопка «Записаться», WhatsApp, Kaspi Pay и 2ГИС — одна страница для маникюра, репетитора, фотографа или любого мастера.',
    keywords: ['мобильная визитка мастер маникюр', 'запись клиентов казахстан', 'визитка репетитор', 'ссылка для мастера instagram'],
    audience: 'Мастера и частные услуги',
    buttons: [
      { icon: '📅', label: 'Записаться' },
      { icon: '💬', label: 'WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС — адрес' },
    ],
  },
  {
    slug: 'almaty',
    title: 'Для бизнеса в Алматы',
    metaTitle: 'Мобильная визитка для бизнеса в Алматы — tapni.kz',
    metaDescription: 'tapni.kz — сервис мобильных визиток для предпринимателей Алматы. Kaspi Pay, 2ГИС, WhatsApp и Telegram в одной ссылке. Бесплатно.',
    h1: 'Мобильная визитка для бизнеса в Алматы',
    subtitle: 'Предприниматели Алматы создают tapni.kz-страницы с Kaspi Pay, 2ГИС и WhatsApp. Одна ссылка для Instagram bio — клиенты сразу видят все контакты.',
    keywords: ['мобильная визитка алматы', 'taplink алматы', 'визитка для бизнеса алматы', 'ссылка instagram алматы'],
    audience: 'Предприниматели Алматы',
    buttons: [
      { icon: '💬', label: 'WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС Алматы' },
      { icon: '✈️', label: 'Telegram' },
    ],
    localBusiness: { city: 'Алматы', regionCode: 'KZ-ALA', lat: 43.238949, lon: 76.889709 },
  },
  {
    slug: 'astana',
    title: 'Для бизнеса в Астане',
    metaTitle: 'Мобильная визитка для бизнеса в Астане — tapni.kz',
    metaDescription: 'tapni.kz — мобильные визитки для предпринимателей Астаны. Kaspi Pay, 2ГИС, WhatsApp и Telegram. Создайте бесплатно за 60 секунд.',
    h1: 'Мобильная визитка для бизнеса в Астане',
    subtitle: 'Создайте tapni.kz-страницу с Kaspi Pay и 2ГИС для вашего бизнеса в Астане. Одна ссылка для Instagram — клиенты сразу видят все контакты.',
    keywords: ['мобильная визитка астана', 'taplink астана', 'визитка для бизнеса астана', 'ссылка instagram астана'],
    audience: 'Предприниматели Астаны',
    buttons: [
      { icon: '💬', label: 'WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС Астана' },
      { icon: '✈️', label: 'Telegram' },
    ],
    localBusiness: { city: 'Астана', regionCode: 'KZ-AKM', lat: 51.169392, lon: 71.449074 },
  },
  {
    slug: 'shymkent',
    title: 'Для бизнеса в Шымкенте',
    metaTitle: 'Мобильная визитка для бизнеса в Шымкенте — tapni.kz',
    metaDescription: 'tapni.kz — мобильные визитки для предпринимателей Шымкента. Kaspi Pay, 2ГИС, WhatsApp. Создайте страницу бесплатно.',
    h1: 'Мобильная визитка для бизнеса в Шымкенте',
    subtitle: 'Создайте tapni.kz-страницу с Kaspi Pay и 2ГИС для вашего бизнеса в Шымкенте. Одна ссылка для Instagram bio.',
    keywords: ['мобильная визитка шымкент', 'taplink шымкент', 'визитка для бизнеса шымкент'],
    audience: 'Предприниматели Шымкента',
    buttons: [
      { icon: '💬', label: 'WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС Шымкент' },
      { icon: '✈️', label: 'Telegram' },
    ],
    localBusiness: { city: 'Шымкент', regionCode: 'KZ-YUZ', lat: 42.317, lon: 69.595 },
  },
  // ─── Новые нишевые страницы ───
  {
    slug: 'salon-krasoty',
    title: 'Для салонов красоты',
    metaTitle: 'Мобильная визитка для салона красоты в Казахстане — tapni.kz',
    metaDescription: 'Создайте страницу для салона красоты с записью в WhatsApp, Kaspi Pay, Instagram и 2ГИС. Одна ссылка для bio — клиенты видят всё и сразу записываются.',
    h1: 'Мобильная визитка для салона красоты',
    subtitle: 'Запись через WhatsApp, Kaspi Pay, Instagram и 2ГИС в одной ссылке. Клиент нажимает в bio — и сразу записывается на маникюр, педикюр или стрижку.',
    keywords: ['визитка салон красоты казахстан', 'ссылка instagram салон красоты', 'запись салон красоты whatsapp', 'taplink салон красоты'],
    audience: 'Салоны красоты и мастера бьюти',
    buttons: [
      { icon: '💬', label: 'Записаться в WhatsApp' },
      { icon: '📸', label: 'Наши работы в Instagram' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС — найти нас' },
    ],
  },
  {
    slug: 'fotografy',
    title: 'Для фотографов',
    metaTitle: 'Мобильная визитка для фотографа в Казахстане — tapni.kz',
    metaDescription: 'Создайте страницу фотографа с портфолио в Instagram, записью в WhatsApp, Kaspi Pay и Telegram. Одна ссылка в bio для всех клиентов.',
    h1: 'Мобильная визитка для фотографа',
    subtitle: 'Портфолио в Instagram, запись через WhatsApp, Kaspi Pay для предоплаты — всё в одной ссылке для bio. Клиент видит работы и сразу бронирует дату.',
    keywords: ['визитка фотограф казахстан', 'ссылка instagram фотограф', 'портфолио фотограф bio link', 'taplink фотограф казахстан'],
    audience: 'Фотографы и видеографы',
    buttons: [
      { icon: '📸', label: 'Портфолио Instagram' },
      { icon: '💬', label: 'Записаться — WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay — предоплата' },
      { icon: '✈️', label: 'Telegram' },
    ],
  },
  {
    slug: 'fitness',
    title: 'Для фитнес-тренеров',
    metaTitle: 'Мобильная визитка для фитнес-тренера в Казахстане — tapni.kz',
    metaDescription: 'Страница фитнес-тренера с записью, Kaspi Pay, Instagram и Telegram. Клиенты видят тренировки, расписание и сразу записываются.',
    h1: 'Мобильная визитка для фитнес-тренера',
    subtitle: 'Расписание тренировок, запись через WhatsApp, Kaspi Pay и TikTok — всё в одной ссылке. Привлекайте новых клиентов из Instagram и TikTok.',
    keywords: ['визитка фитнес тренер казахстан', 'ссылка instagram тренер', 'персональный тренер bio link', 'онлайн тренер визитка'],
    audience: 'Фитнес-тренеры и инструкторы',
    buttons: [
      { icon: '💬', label: 'Записаться — WhatsApp' },
      { icon: '💳', label: 'Оплата Kaspi Pay' },
      { icon: '🎵', label: 'TikTok — тренировки' },
      { icon: '📸', label: 'Instagram' },
    ],
  },
  {
    slug: 'nedvizhimost',
    title: 'Для агентов недвижимости',
    metaTitle: 'Мобильная визитка для агента по недвижимости в Казахстане — tapni.kz',
    metaDescription: 'Создайте страницу агента недвижимости с Krisha.kz, WhatsApp, Kaspi Pay и 2ГИС. Клиенты находят ваши объявления и сразу связываются.',
    h1: 'Мобильная визитка для агента по недвижимости',
    subtitle: 'Krisha.kz объявления, WhatsApp, 2ГИС и Kaspi Pay в одной ссылке. Отправьте ссылку клиенту — он видит все ваши объекты и контакты.',
    keywords: ['визитка агент недвижимость казахстан', 'риелтор ссылка instagram', 'krisha.kz визитка', 'агент недвижимости bio link'],
    audience: 'Агенты и риелторы недвижимости',
    buttons: [
      { icon: '🏠', label: 'Мои объекты на Krisha.kz' },
      { icon: '💬', label: 'WhatsApp — написать' },
      { icon: '📞', label: 'Позвонить' },
      { icon: '📍', label: '2ГИС — офис' },
    ],
  },
  {
    slug: 'avto',
    title: 'Для автосервиса и продажи авто',
    metaTitle: 'Мобильная визитка для автосервиса и автопродажи — tapni.kz',
    metaDescription: 'Создайте страницу для автосервиса или продажи авто с Kolesa.kz, WhatsApp, 2ГИС и Kaspi Pay. Клиенты находят вас и сразу звонят.',
    h1: 'Мобильная визитка для автосервиса',
    subtitle: 'Kolesa.kz объявления, WhatsApp, 2ГИС и Kaspi Pay в одной ссылке. Покупатели и клиенты автосервиса сразу видят все ваши контакты.',
    keywords: ['визитка автосервис казахстан', 'продажа авто визитка', 'kolesa.kz ссылка instagram', 'автосервис bio link whatsapp'],
    audience: 'Автосервисы и продавцы авто',
    buttons: [
      { icon: '🚗', label: 'Мои авто на Kolesa.kz' },
      { icon: '💬', label: 'WhatsApp — спросить' },
      { icon: '📞', label: 'Позвонить' },
      { icon: '📍', label: '2ГИС — сервис' },
    ],
  },
  {
    slug: 'dostavka',
    title: 'Для служб доставки',
    metaTitle: 'Мобильная визитка для доставки и курьерской службы — tapni.kz',
    metaDescription: 'Создайте страницу для службы доставки с WhatsApp-заказом, Kaspi Pay, Telegram и 2ГИС. Клиенты заказывают доставку прямо из Instagram.',
    h1: 'Мобильная визитка для службы доставки',
    subtitle: 'Заказ через WhatsApp, Kaspi Pay, Telegram и меню в одной ссылке. Клиент нажимает в bio — и сразу делает заказ на доставку.',
    keywords: ['визитка доставка казахстан', 'доставка еды instagram bio', 'курьерская служба ссылка', 'заказ доставка whatsapp'],
    audience: 'Службы доставки еды и товаров',
    buttons: [
      { icon: '💬', label: 'Заказать в WhatsApp' },
      { icon: '✈️', label: 'Telegram — заказ' },
      { icon: '💳', label: 'Kaspi Pay — оплата' },
      { icon: '📋', label: 'Наше меню' },
    ],
  },
  // ─── Новые городские страницы ───
  {
    slug: 'aktobe',
    title: 'Для бизнеса в Актобе',
    metaTitle: 'Мобильная визитка для бизнеса в Актобе — tapni.kz',
    metaDescription: 'tapni.kz — мобильные визитки для предпринимателей Актобе. Kaspi Pay, 2ГИС, WhatsApp и Telegram. Создайте страницу бесплатно за 60 секунд.',
    h1: 'Мобильная визитка для бизнеса в Актобе',
    subtitle: 'Предприниматели Актобе создают tapni.kz-страницы с Kaspi Pay, 2ГИС и WhatsApp. Одна ссылка — все контакты.',
    keywords: ['мобильная визитка актобе', 'taplink актобе', 'визитка для бизнеса актобе', 'ссылка instagram актобе'],
    audience: 'Предприниматели Актобе',
    buttons: [
      { icon: '💬', label: 'WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС Актобе' },
      { icon: '✈️', label: 'Telegram' },
    ],
    localBusiness: { city: 'Актобе', regionCode: 'KZ-AKT', lat: 50.27972, lon: 57.20694 },
  },
  {
    slug: 'karaganda',
    title: 'Для бизнеса в Карагандe',
    metaTitle: 'Мобильная визитка для бизнеса в Карагандe — tapni.kz',
    metaDescription: 'tapni.kz — мобильные визитки для предпринимателей Караганды. Kaspi Pay, 2ГИС, WhatsApp. Создайте страницу бесплатно.',
    h1: 'Мобильная визитка для бизнеса в Карагандe',
    subtitle: 'Создайте tapni.kz-страницу для вашего бизнеса в Карагандe с Kaspi Pay, 2ГИС и WhatsApp.',
    keywords: ['мобильная визитка караганда', 'taplink караганда', 'визитка для бизнеса караганда'],
    audience: 'Предприниматели Карагандины',
    buttons: [
      { icon: '💬', label: 'WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС Караганда' },
      { icon: '✈️', label: 'Telegram' },
    ],
    localBusiness: { city: 'Караганда', regionCode: 'KZ-KAR', lat: 49.80648, lon: 73.08858 },
  },
  {
    slug: 'atyrau',
    title: 'Для бизнеса в Атырау',
    metaTitle: 'Мобильная визитка для бизнеса в Атырау — tapni.kz',
    metaDescription: 'tapni.kz — мобильные визитки для предпринимателей Атырау. Kaspi Pay, 2ГИС, WhatsApp. Создайте страницу бесплатно.',
    h1: 'Мобильная визитка для бизнеса в Атырау',
    subtitle: 'Создайте tapni.kz-страницу с Kaspi Pay и 2ГИС для вашего бизнеса в Атырау. Одна ссылка для Instagram bio.',
    keywords: ['мобильная визитка атырау', 'taplink атырау', 'визитка для бизнеса атырау'],
    audience: 'Предприниматели Атырау',
    buttons: [
      { icon: '💬', label: 'WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС Атырау' },
      { icon: '✈️', label: 'Telegram' },
    ],
    localBusiness: { city: 'Атырау', regionCode: 'KZ-ATY', lat: 47.10942, lon: 51.92353 },
  },
  {
    slug: 'kostanay',
    title: 'Для бизнеса в Костанае',
    metaTitle: 'Мобильная визитка для бизнеса в Костанае — tapni.kz',
    metaDescription: 'tapni.kz — мобильные визитки для предпринимателей Костаная. Kaspi Pay, 2ГИС, WhatsApp. Создайте страницу бесплатно.',
    h1: 'Мобильная визитка для бизнеса в Костанае',
    subtitle: 'Создайте tapni.kz-страницу с Kaspi Pay и 2ГИС для вашего бизнеса в Костанае.',
    keywords: ['мобильная визитка костанай', 'taplink костанай', 'визитка для бизнеса костанай'],
    audience: 'Предприниматели Костаная',
    buttons: [
      { icon: '💬', label: 'WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС Костанай' },
      { icon: '✈️', label: 'Telegram' },
    ],
    localBusiness: { city: 'Костанай', regionCode: 'KZ-KUS', lat: 53.21435, lon: 63.62861 },
  },
  {
    slug: 'pavlodar',
    title: 'Для бизнеса в Павлодаре',
    metaTitle: 'Мобильная визитка для бизнеса в Павлодаре — tapni.kz',
    metaDescription: 'tapni.kz — мобильные визитки для предпринимателей Павлодара. Kaspi Pay, 2ГИС, WhatsApp. Создайте страницу бесплатно.',
    h1: 'Мобильная визитка для бизнеса в Павлодаре',
    subtitle: 'Создайте tapni.kz-страницу с Kaspi Pay и 2ГИС для вашего бизнеса в Павлодаре.',
    keywords: ['мобильная визитка павлодар', 'taplink павлодар', 'визитка для бизнеса павлодар'],
    audience: 'Предприниматели Павлодара',
    buttons: [
      { icon: '💬', label: 'WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС Павлодар' },
      { icon: '✈️', label: 'Telegram' },
    ],
    localBusiness: { city: 'Павлодар', regionCode: 'KZ-PAV', lat: 52.28554, lon: 76.96766 },
  },
  {
    slug: 'semey',
    title: 'Для бизнеса в Семее',
    metaTitle: 'Мобильная визитка для бизнеса в Семее — tapni.kz',
    metaDescription: 'tapni.kz — мобильные визитки для предпринимателей Семея. Kaspi Pay, 2ГИС, WhatsApp. Создайте страницу бесплатно.',
    h1: 'Мобильная визитка для бизнеса в Семее',
    subtitle: 'Создайте tapni.kz-страницу с Kaspi Pay и 2ГИС для вашего бизнеса в Семее.',
    keywords: ['мобильная визитка семей', 'taplink семей', 'визитка для бизнеса семей'],
    audience: 'Предприниматели Семея',
    buttons: [
      { icon: '💬', label: 'WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС Семей' },
      { icon: '✈️', label: 'Telegram' },
    ],
    localBusiness: { city: 'Семей', regionCode: 'KZ-VOS', lat: 50.41184, lon: 80.22676 },
  },
  {
    slug: 'taraz',
    title: 'Для бизнеса в Таразе',
    metaTitle: 'Мобильная визитка для бизнеса в Таразе — tapni.kz',
    metaDescription: 'tapni.kz — мобильные визитки для предпринимателей Тараза. Kaspi Pay, 2ГИС, WhatsApp. Создайте страницу бесплатно.',
    h1: 'Мобильная визитка для бизнеса в Таразе',
    subtitle: 'Создайте tapni.kz-страницу с Kaspi Pay и 2ГИС для вашего бизнеса в Таразе.',
    keywords: ['мобильная визитка тараз', 'taplink тараз', 'визитка для бизнеса тараз'],
    audience: 'Предприниматели Тараза',
    buttons: [
      { icon: '💬', label: 'WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС Тараз' },
      { icon: '✈️', label: 'Telegram' },
    ],
    localBusiness: { city: 'Тараз', regionCode: 'KZ-ZHA', lat: 42.90072, lon: 71.36427 },
  },
  // ─── Kaspi + соцсети ───
  {
    slug: 'kaspi-magazin',
    title: 'Ссылка на Kaspi магазин',
    metaTitle: 'Ссылка на Kaspi магазин в Instagram и TikTok — tapni.kz',
    metaDescription: 'Поставьте ссылку на ваш Kaspi магазин в bio Instagram или TikTok. tapni.kz — страница с кнопкой прямо в Kaspi магазин, Kaspi Pay и WhatsApp. Бесплатно.',
    h1: 'Ссылка на Kaspi магазин для Instagram и TikTok',
    subtitle: 'Instagram и TikTok дают один слот для ссылки в bio. tapni.kz упаковывает туда кнопку прямо в ваш Kaspi магазин, Kaspi Pay для прямых оплат, WhatsApp для вопросов и 2ГИС для пункта выдачи — всё в одном адресе.',
    keywords: [
      'ссылка kaspi магазин instagram', 'kaspi магазин bio', 'kaspi shop ссылка в инстаграм',
      'как поставить kaspi магазин в instagram', 'ссылка на kaspi магазин', 'kaspi.kz магазин ссылка bio',
      'kaspi магазин tiktok ссылка', 'kaspi магазин соцсети ссылка',
    ],
    audience: 'Продавцы Kaspi магазина',
    buttons: [
      { icon: '🛒', label: 'Мой Kaspi магазин' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '💬', label: 'WhatsApp — вопрос' },
      { icon: '📍', label: '2ГИС — пункт выдачи' },
    ],
  },
  {
    slug: 'prodazhi-kaspi',
    title: 'Продвижение Kaspi магазина через соцсети',
    metaTitle: 'Как привлечь покупателей в Kaspi магазин через Instagram и TikTok',
    metaDescription: 'Продвигайте Kaspi магазин через Instagram и TikTok: одна ссылка в bio ведёт прямо к вашим товарам. Привлекайте покупателей из соцсетей в Kaspi без рекламы.',
    h1: 'Как привлечь покупателей в Kaspi магазин через соцсети',
    subtitle: 'Большинство Kaspi-продавцов теряют покупателей: ведут Instagram и TikTok, но не дают удобную ссылку на магазин. tapni.kz — страница с кнопкой «Мой Kaspi магазин», Kaspi Pay и WhatsApp. Поставьте в bio — покупатели из соцсетей идут прямо к вашим товарам.',
    keywords: [
      'как привлечь покупателей kaspi', 'kaspi магазин продвижение instagram', 'kaspi магазин tiktok',
      'kaspi продавец соцсети', 'продажи kaspi через instagram', 'продажи kaspi через tiktok',
      'привлечь клиентов kaspi', 'kaspi shop instagram продвижение', 'kaspi продавец соц сети',
      'продавать на kaspi через instagram', 'kaspi магазин продажи соцсети',
    ],
    audience: 'Продавцы Kaspi.kz',
    buttons: [
      { icon: '🛒', label: 'Kaspi магазин' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '💬', label: 'WhatsApp — вопрос' },
      { icon: '🎵', label: 'TikTok' },
    ],
  },
  // ─── Страницы под косвенный трафик ───
  {
    slug: 'kak-privlech-klientov',
    title: 'Как привлечь клиентов',
    metaTitle: 'Как привлечь клиентов через Instagram в Казахстане — tapni.kz',
    metaDescription: 'Практическое руководство: как привлекать клиентов через Instagram, WhatsApp и 2ГИС для малого бизнеса в Казахстане. Одна ссылка — все контакты клиентов.',
    h1: 'Как привлечь клиентов через Instagram',
    subtitle: 'Главная ошибка бизнеса в Instagram — нет одного места, куда клиент попадает и сразу действует. tapni.kz — это страница с кнопками WhatsApp, Kaspi Pay и 2ГИС, которую вы ставите в bio. Клиент нажал — позвонил, заказал, оплатил.',
    keywords: ['как привлечь клиентов instagram', 'привлечение клиентов казахстан', 'привлечь покупателей instagram', 'клиенты через instagram бизнес казахстан', 'онлайн продвижение малый бизнес', 'как найти клиентов instagram'],
    audience: 'Малый бизнес и предприниматели',
    buttons: [
      { icon: '💬', label: 'WhatsApp — написать' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС — найти нас' },
      { icon: '✈️', label: 'Telegram-канал' },
    ],
  },
  {
    slug: 'prodazhi-instagram',
    title: 'Продажи через Instagram',
    metaTitle: 'Как продавать через Instagram в Казахстане — tapni.kz',
    metaDescription: 'Как настроить продажи через Instagram в Казахстане: ссылка в bio, Kaspi Pay, WhatsApp-заказы. Готовая страница для приёма заказов за 60 секунд.',
    h1: 'Как продавать через Instagram в Казахстане',
    subtitle: 'Instagram не даёт ставить ссылки в постах — только в bio. tapni.kz — страница с кнопками «Заказать в WhatsApp», «Оплатить Kaspi Pay» и «Наш магазин Kaspi». Покупатель видит всё нужное и сразу покупает.',
    keywords: ['продажи через instagram казахстан', 'как продавать в instagram', 'онлайн продажи казахстан', 'instagram магазин казахстан', 'продажи через whatsapp', 'как принимать заказы instagram'],
    audience: 'Продавцы и интернет-магазины',
    buttons: [
      { icon: '💬', label: 'Заказать в WhatsApp' },
      { icon: '🛒', label: 'Kaspi магазин' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📸', label: 'Наши товары' },
    ],
  },
  {
    slug: 'ssylka-v-bio',
    title: 'Ссылка в bio Instagram',
    metaTitle: 'Что поставить в ссылку bio Instagram — лучшие варианты 2025',
    metaDescription: 'Что лучше поставить в ссылку в bio Instagram: Taplink, Linktree или tapni.kz? Сравниваем и объясняем почему казахстанский сервис выгоднее для бизнеса.',
    h1: 'Что поставить в ссылку в bio Instagram',
    subtitle: 'В Instagram только одна ссылка в профиле. tapni.kz превращает её в страницу со всеми контактами: WhatsApp, Kaspi Pay, 2ГИС, Telegram, телефон — клиент нажимает нужную кнопку сразу.',
    keywords: ['ссылка в bio instagram', 'что поставить в bio instagram', 'как сделать ссылку в instagram', 'taplink альтернатива', 'linktree казахстан', 'ссылка в шапке instagram', 'bio link instagram казахстан', 'что написать в bio instagram'],
    audience: 'Блогеры и предприниматели',
    buttons: [
      { icon: '💬', label: 'WhatsApp' },
      { icon: '📸', label: 'Instagram' },
      { icon: '✈️', label: 'Telegram' },
      { icon: '💳', label: 'Kaspi Pay' },
    ],
  },
  {
    slug: 'biznes-instagram',
    title: 'Бизнес через Instagram',
    metaTitle: 'Как вести бизнес через Instagram в Казахстане — tapni.kz',
    metaDescription: 'Как запустить и развивать бизнес через Instagram в Казахстане: Kaspi Pay, WhatsApp-продажи, 2ГИС и ссылка в bio. Готовая страница за 60 секунд.',
    h1: 'Как вести бизнес через Instagram в Казахстане',
    subtitle: 'Instagram — главный канал продаж малого бизнеса в Казахстане. tapni.kz — ваша посадочная страница: клиент нажимает в bio и сразу видит Kaspi Pay, WhatsApp, адрес в 2ГИС и ваш магазин. Ни сайта, ни программиста не нужно.',
    keywords: ['бизнес через instagram казахстан', 'как вести бизнес в instagram', 'малый бизнес instagram казахстан', 'онлайн бизнес казахстан', 'продвижение бизнеса instagram', 'instagram для бизнеса казахстан', 'подписчики instagram бизнес'],
    audience: 'Начинающие предприниматели',
    buttons: [
      { icon: '💬', label: 'WhatsApp — написать' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '🛒', label: 'Kaspi магазин' },
      { icon: '📍', label: '2ГИС — адрес' },
    ],
  },
]

export const NICHE_SLUGS = NICHE_PAGES.map((p) => p.slug)
