export interface NichePage {
  slug: string
  title: string
  metaTitle: string
  metaDescription: string
  h1: string
  subtitle: string
  keywords: string[]
  audience: string
  buttons: { icon: string; label: string }[]
  localBusiness?: {
    city: string
    regionCode: string
    lat?: number
    lon?: number
  }
}

export const NICHE_PAGES: NichePage[] = [
  {
    slug: 'kaspi-prodavets',
    title: 'Для продавцов Kaspi',
    metaTitle: 'Мобильная визитка для продавцов Kaspi — tapni.kz',
    metaDescription: 'Создайте страницу с Kaspi магазин, Kaspi Pay и WhatsApp для вашего Kaspi-магазина. Одна ссылка в шапке — клиенты сразу видят ваш магазин и товары.',
    h1: 'Мобильная визитка для продавца Kaspi',
    subtitle: 'Одна ссылка с Kaspi магазин, Kaspi Pay, WhatsApp и 2ГИС. Вставьте в описание вашего Kaspi-магазина — клиенты сразу найдут всё нужное.',
    keywords: ['ссылка для kaspi магазина', 'визитка продавца kaspi', 'taplink для kaspi', 'kaspi продавец страница'],
    audience: 'Продавцы Kaspi',
    buttons: [
      { icon: '🛒', label: 'Kaspi магазин' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '💬', label: 'WhatsApp' },
      { icon: '📍', label: '2ГИС — маршрут' },
    ],
  },
  {
    slug: 'instagram-bloger',
    title: 'Для Instagram блогеров',
    metaTitle: 'Ссылка в bio Instagram для блогеров Казахстана — tapni.kz',
    metaDescription: 'Лучший Taplink для Instagram-блогеров в Казахстане. Добавьте TikTok, Telegram-канал, YouTube и ссылку на донат в одно место.',
    h1: 'Ссылка в bio Instagram для блогеров',
    subtitle: 'Один адрес вместо 10 ссылок. Подписчики нажимают — попадают на ваш Telegram-канал, TikTok, YouTube и сотрудничество.',
    keywords: ['ссылка в bio instagram', 'taplink казахстан блогер', 'линк в инстаграм', 'bio link instagram казахстан'],
    audience: 'Блогеры и инфлюенсеры',
    buttons: [
      { icon: '📸', label: 'Instagram' },
      { icon: '🎵', label: 'TikTok' },
      { icon: '✈️', label: 'Telegram-канал' },
      { icon: '▶️', label: 'YouTube' },
    ],
  },
  {
    slug: 'kafe-restoran',
    title: 'Для кафе и ресторанов',
    metaTitle: 'Мобильная визитка для кафе и ресторана в Казахстане — tapni.kz',
    metaDescription: 'Создайте страницу для кафе с меню, 2ГИС, WhatsApp и Kaspi Pay. Клиенты видят расписание и могут сразу записаться или оплатить.',
    h1: 'Мобильная визитка для кафе и ресторана',
    subtitle: 'Меню, 2ГИС, WhatsApp-заказ, Kaspi Pay — всё в одной ссылке для Instagram. Клиент нажимает и сразу строит маршрут к вам.',
    keywords: ['мобильная визитка кафе казахстан', 'ссылка для ресторана instagram', 'меню кафе qr-код', 'taplink кафе'],
    audience: 'Кафе и рестораны',
    buttons: [
      { icon: '📋', label: 'Меню' },
      { icon: '📍', label: '2ГИС — найти нас' },
      { icon: '💬', label: 'WhatsApp заказ' },
      { icon: '💳', label: 'Kaspi Pay' },
    ],
  },
  {
    slug: 'master-uslugi',
    title: 'Для мастеров и услуг',
    metaTitle: 'Мобильная визитка для мастеров — маникюр, репетитор, мастер — tapni.kz',
    metaDescription: 'Создайте страницу для записи клиентов. Кнопка "Записаться", WhatsApp, 2ГИС и Kaspi Pay — клиент сам запишется и найдёт вас.',
    h1: 'Мобильная визитка для мастеров и частных услуг',
    subtitle: 'Кнопка «Записаться», WhatsApp, Kaspi Pay и 2ГИС — одна страница для маникюра, репетитора, фотографа или любого мастера.',
    keywords: ['мобильная визитка мастер маникюр', 'запись клиентов казахстан', 'визитка репетитор', 'ссылка для мастера instagram'],
    audience: 'Мастера и частные услуги',
    buttons: [
      { icon: '📅', label: 'Записаться' },
      { icon: '💬', label: 'WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС — адрес' },
    ],
  },
  {
    slug: 'almaty',
    title: 'Для бизнеса в Алматы',
    metaTitle: 'Мобильная визитка для бизнеса в Алматы — tapni.kz',
    metaDescription: 'tapni.kz — сервис мобильных визиток для предпринимателей Алматы. Kaspi Pay, 2ГИС, WhatsApp и Telegram в одной ссылке. Бесплатно.',
    h1: 'Мобильная визитка для бизнеса в Алматы',
    subtitle: 'Предприниматели Алматы создают tapni.kz-страницы с Kaspi Pay, 2ГИС и WhatsApp. Одна ссылка для Instagram bio — клиенты сразу видят все контакты.',
    keywords: ['мобильная визитка алматы', 'taplink алматы', 'визитка для бизнеса алматы', 'ссылка instagram алматы'],
    audience: 'Предприниматели Алматы',
    buttons: [
      { icon: '💬', label: 'WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС Алматы' },
      { icon: '✈️', label: 'Telegram' },
    ],
    localBusiness: { city: 'Алматы', regionCode: 'KZ-ALA', lat: 43.238949, lon: 76.889709 },
  },
  {
    slug: 'astana',
    title: 'Для бизнеса в Астане',
    metaTitle: 'Мобильная визитка для бизнеса в Астане — tapni.kz',
    metaDescription: 'tapni.kz — мобильные визитки для предпринимателей Астаны. Kaspi Pay, 2ГИС, WhatsApp и Telegram. Создайте бесплатно за 60 секунд.',
    h1: 'Мобильная визитка для бизнеса в Астане',
    subtitle: 'Создайте tapni.kz-страницу с Kaspi Pay и 2ГИС для вашего бизнеса в Астане. Одна ссылка для Instagram — клиенты сразу видят все контакты.',
    keywords: ['мобильная визитка астана', 'taplink астана', 'визитка для бизнеса астана', 'ссылка instagram астана'],
    audience: 'Предприниматели Астаны',
    buttons: [
      { icon: '💬', label: 'WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС Астана' },
      { icon: '✈️', label: 'Telegram' },
    ],
    localBusiness: { city: 'Астана', regionCode: 'KZ-AKM', lat: 51.169392, lon: 71.449074 },
  },
  {
    slug: 'shymkent',
    title: 'Для бизнеса в Шымкенте',
    metaTitle: 'Мобильная визитка для бизнеса в Шымкенте — tapni.kz',
    metaDescription: 'tapni.kz — мобильные визитки для предпринимателей Шымкента. Kaspi Pay, 2ГИС, WhatsApp. Создайте страницу бесплатно.',
    h1: 'Мобильная визитка для бизнеса в Шымкенте',
    subtitle: 'Создайте tapni.kz-страницу с Kaspi Pay и 2ГИС для вашего бизнеса в Шымкенте. Одна ссылка для Instagram bio.',
    keywords: ['мобильная визитка шымкент', 'taplink шымкент', 'визитка для бизнеса шымкент'],
    audience: 'Предприниматели Шымкента',
    buttons: [
      { icon: '💬', label: 'WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС Шымкент' },
      { icon: '✈️', label: 'Telegram' },
    ],
    localBusiness: { city: 'Шымкент', regionCode: 'KZ-YUZ', lat: 42.317, lon: 69.595 },
  },
  // ─── Новые нишевые страницы ───
  {
    slug: 'salon-krasoty',
    title: 'Для салонов красоты',
    metaTitle: 'Мобильная визитка для салона красоты в Казахстане — tapni.kz',
    metaDescription: 'Создайте страницу для салона красоты с записью в WhatsApp, Kaspi Pay, Instagram и 2ГИС. Одна ссылка для bio — клиенты видят всё и сразу записываются.',
    h1: 'Мобильная визитка для салона красоты',
    subtitle: 'Запись через WhatsApp, Kaspi Pay, Instagram и 2ГИС в одной ссылке. Клиент нажимает в bio — и сразу записывается на маникюр, педикюр или стрижку.',
    keywords: ['визитка салон красоты казахстан', 'ссылка instagram салон красоты', 'запись салон красоты whatsapp', 'taplink салон красоты'],
    audience: 'Салоны красоты и мастера бьюти',
    buttons: [
      { icon: '💬', label: 'Записаться в WhatsApp' },
      { icon: '📸', label: 'Наши работы в Instagram' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС — найти нас' },
    ],
  },
  {
    slug: 'fotografy',
    title: 'Для фотографов',
    metaTitle: 'Мобильная визитка для фотографа в Казахстане — tapni.kz',
    metaDescription: 'Создайте страницу фотографа с портфолио в Instagram, записью в WhatsApp, Kaspi Pay и Telegram. Одна ссылка в bio для всех клиентов.',
    h1: 'Мобильная визитка для фотографа',
    subtitle: 'Портфолио в Instagram, запись через WhatsApp, Kaspi Pay для предоплаты — всё в одной ссылке для bio. Клиент видит работы и сразу бронирует дату.',
    keywords: ['визитка фотограф казахстан', 'ссылка instagram фотограф', 'портфолио фотограф bio link', 'taplink фотограф казахстан'],
    audience: 'Фотографы и видеографы',
    buttons: [
      { icon: '📸', label: 'Портфолио Instagram' },
      { icon: '💬', label: 'Записаться — WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay — предоплата' },
      { icon: '✈️', label: 'Telegram' },
    ],
  },
  {
    slug: 'fitness',
    title: 'Для фитнес-тренеров',
    metaTitle: 'Мобильная визитка для фитнес-тренера в Казахстане — tapni.kz',
    metaDescription: 'Страница фитнес-тренера с записью, Kaspi Pay, Instagram и Telegram. Клиенты видят тренировки, расписание и сразу записываются.',
    h1: 'Мобильная визитка для фитнес-тренера',
    subtitle: 'Расписание тренировок, запись через WhatsApp, Kaspi Pay и TikTok — всё в одной ссылке. Привлекайте новых клиентов из Instagram и TikTok.',
    keywords: ['визитка фитнес тренер казахстан', 'ссылка instagram тренер', 'персональный тренер bio link', 'онлайн тренер визитка'],
    audience: 'Фитнес-тренеры и инструкторы',
    buttons: [
      { icon: '💬', label: 'Записаться — WhatsApp' },
      { icon: '💳', label: 'Оплата Kaspi Pay' },
      { icon: '🎵', label: 'TikTok — тренировки' },
      { icon: '📸', label: 'Instagram' },
    ],
  },
  {
    slug: 'nedvizhimost',
    title: 'Для агентов недвижимости',
    metaTitle: 'Мобильная визитка для агента по недвижимости в Казахстане — tapni.kz',
    metaDescription: 'Создайте страницу агента недвижимости с Krisha.kz, WhatsApp, Kaspi Pay и 2ГИС. Клиенты находят ваши объявления и сразу связываются.',
    h1: 'Мобильная визитка для агента по недвижимости',
    subtitle: 'Krisha.kz объявления, WhatsApp, 2ГИС и Kaspi Pay в одной ссылке. Отправьте ссылку клиенту — он видит все ваши объекты и контакты.',
    keywords: ['визитка агент недвижимость казахстан', 'риелтор ссылка instagram', 'krisha.kz визитка', 'агент недвижимости bio link'],
    audience: 'Агенты и риелторы недвижимости',
    buttons: [
      { icon: '🏠', label: 'Мои объекты на Krisha.kz' },
      { icon: '💬', label: 'WhatsApp — написать' },
      { icon: '📞', label: 'Позвонить' },
      { icon: '📍', label: '2ГИС — офис' },
    ],
  },
  {
    slug: 'avto',
    title: 'Для автосервиса и продажи авто',
    metaTitle: 'Мобильная визитка для автосервиса и автопродажи — tapni.kz',
    metaDescription: 'Создайте страницу для автосервиса или продажи авто с Kolesa.kz, WhatsApp, 2ГИС и Kaspi Pay. Клиенты находят вас и сразу звонят.',
    h1: 'Мобильная визитка для автосервиса',
    subtitle: 'Kolesa.kz объявления, WhatsApp, 2ГИС и Kaspi Pay в одной ссылке. Покупатели и клиенты автосервиса сразу видят все ваши контакты.',
    keywords: ['визитка автосервис казахстан', 'продажа авто визитка', 'kolesa.kz ссылка instagram', 'автосервис bio link whatsapp'],
    audience: 'Автосервисы и продавцы авто',
    buttons: [
      { icon: '🚗', label: 'Мои авто на Kolesa.kz' },
      { icon: '💬', label: 'WhatsApp — спросить' },
      { icon: '📞', label: 'Позвонить' },
      { icon: '📍', label: '2ГИС — сервис' },
    ],
  },
  {
    slug: 'dostavka',
    title: 'Для служб доставки',
    metaTitle: 'Мобильная визитка для доставки и курьерской службы — tapni.kz',
    metaDescription: 'Создайте страницу для службы доставки с WhatsApp-заказом, Kaspi Pay, Telegram и 2ГИС. Клиенты заказывают доставку прямо из Instagram.',
    h1: 'Мобильная визитка для службы доставки',
    subtitle: 'Заказ через WhatsApp, Kaspi Pay, Telegram и меню в одной ссылке. Клиент нажимает в bio — и сразу делает заказ на доставку.',
    keywords: ['визитка доставка казахстан', 'доставка еды instagram bio', 'курьерская служба ссылка', 'заказ доставка whatsapp'],
    audience: 'Службы доставки еды и товаров',
    buttons: [
      { icon: '💬', label: 'Заказать в WhatsApp' },
      { icon: '✈️', label: 'Telegram — заказ' },
      { icon: '💳', label: 'Kaspi Pay — оплата' },
      { icon: '📋', label: 'Наше меню' },
    ],
  },
  // ─── Новые городские страницы ───
  {
    slug: 'aktobe',
    title: 'Для бизнеса в Актобе',
    metaTitle: 'Мобильная визитка для бизнеса в Актобе — tapni.kz',
    metaDescription: 'tapni.kz — мобильные визитки для предпринимателей Актобе. Kaspi Pay, 2ГИС, WhatsApp и Telegram. Создайте страницу бесплатно за 60 секунд.',
    h1: 'Мобильная визитка для бизнеса в Актобе',
    subtitle: 'Предприниматели Актобе создают tapni.kz-страницы с Kaspi Pay, 2ГИС и WhatsApp. Одна ссылка — все контакты.',
    keywords: ['мобильная визитка актобе', 'taplink актобе', 'визитка для бизнеса актобе', 'ссылка instagram актобе'],
    audience: 'Предприниматели Актобе',
    buttons: [
      { icon: '💬', label: 'WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС Актобе' },
      { icon: '✈️', label: 'Telegram' },
    ],
    localBusiness: { city: 'Актобе', regionCode: 'KZ-AKT', lat: 50.27972, lon: 57.20694 },
  },
  {
    slug: 'karaganda',
    title: 'Для бизнеса в Карагандe',
    metaTitle: 'Мобильная визитка для бизнеса в Карагандe — tapni.kz',
    metaDescription: 'tapni.kz — мобильные визитки для предпринимателей Караганды. Kaspi Pay, 2ГИС, WhatsApp. Создайте страницу бесплатно.',
    h1: 'Мобильная визитка для бизнеса в Карагандe',
    subtitle: 'Создайте tapni.kz-страницу для вашего бизнеса в Карагандe с Kaspi Pay, 2ГИС и WhatsApp.',
    keywords: ['мобильная визитка караганда', 'taplink караганда', 'визитка для бизнеса караганда'],
    audience: 'Предприниматели Карагандины',
    buttons: [
      { icon: '💬', label: 'WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС Караганда' },
      { icon: '✈️', label: 'Telegram' },
    ],
    localBusiness: { city: 'Караганда', regionCode: 'KZ-KAR', lat: 49.80648, lon: 73.08858 },
  },
  {
    slug: 'atyrau',
    title: 'Для бизнеса в Атырау',
    metaTitle: 'Мобильная визитка для бизнеса в Атырау — tapni.kz',
    metaDescription: 'tapni.kz — мобильные визитки для предпринимателей Атырау. Kaspi Pay, 2ГИС, WhatsApp. Создайте страницу бесплатно.',
    h1: 'Мобильная визитка для бизнеса в Атырау',
    subtitle: 'Создайте tapni.kz-страницу с Kaspi Pay и 2ГИС для вашего бизнеса в Атырау. Одна ссылка для Instagram bio.',
    keywords: ['мобильная визитка атырау', 'taplink атырау', 'визитка для бизнеса атырау'],
    audience: 'Предприниматели Атырау',
    buttons: [
      { icon: '💬', label: 'WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС Атырау' },
      { icon: '✈️', label: 'Telegram' },
    ],
    localBusiness: { city: 'Атырау', regionCode: 'KZ-ATY', lat: 47.10942, lon: 51.92353 },
  },
  {
    slug: 'kostanay',
    title: 'Для бизнеса в Костанае',
    metaTitle: 'Мобильная визитка для бизнеса в Костанае — tapni.kz',
    metaDescription: 'tapni.kz — мобильные визитки для предпринимателей Костаная. Kaspi Pay, 2ГИС, WhatsApp. Создайте страницу бесплатно.',
    h1: 'Мобильная визитка для бизнеса в Костанае',
    subtitle: 'Создайте tapni.kz-страницу с Kaspi Pay и 2ГИС для вашего бизнеса в Костанае.',
    keywords: ['мобильная визитка костанай', 'taplink костанай', 'визитка для бизнеса костанай'],
    audience: 'Предприниматели Костаная',
    buttons: [
      { icon: '💬', label: 'WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС Костанай' },
      { icon: '✈️', label: 'Telegram' },
    ],
    localBusiness: { city: 'Костанай', regionCode: 'KZ-KUS', lat: 53.21435, lon: 63.62861 },
  },
  {
    slug: 'pavlodar',
    title: 'Для бизнеса в Павлодаре',
    metaTitle: 'Мобильная визитка для бизнеса в Павлодаре — tapni.kz',
    metaDescription: 'tapni.kz — мобильные визитки для предпринимателей Павлодара. Kaspi Pay, 2ГИС, WhatsApp. Создайте страницу бесплатно.',
    h1: 'Мобильная визитка для бизнеса в Павлодаре',
    subtitle: 'Создайте tapni.kz-страницу с Kaspi Pay и 2ГИС для вашего бизнеса в Павлодаре.',
    keywords: ['мобильная визитка павлодар', 'taplink павлодар', 'визитка для бизнеса павлодар'],
    audience: 'Предприниматели Павлодара',
    buttons: [
      { icon: '💬', label: 'WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС Павлодар' },
      { icon: '✈️', label: 'Telegram' },
    ],
    localBusiness: { city: 'Павлодар', regionCode: 'KZ-PAV', lat: 52.28554, lon: 76.96766 },
  },
  {
    slug: 'semey',
    title: 'Для бизнеса в Семее',
    metaTitle: 'Мобильная визитка для бизнеса в Семее — tapni.kz',
    metaDescription: 'tapni.kz — мобильные визитки для предпринимателей Семея. Kaspi Pay, 2ГИС, WhatsApp. Создайте страницу бесплатно.',
    h1: 'Мобильная визитка для бизнеса в Семее',
    subtitle: 'Создайте tapni.kz-страницу с Kaspi Pay и 2ГИС для вашего бизнеса в Семее.',
    keywords: ['мобильная визитка семей', 'taplink семей', 'визитка для бизнеса семей'],
    audience: 'Предприниматели Семея',
    buttons: [
      { icon: '💬', label: 'WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС Семей' },
      { icon: '✈️', label: 'Telegram' },
    ],
    localBusiness: { city: 'Семей', regionCode: 'KZ-VOS', lat: 50.41184, lon: 80.22676 },
  },
  {
    slug: 'taraz',
    title: 'Для бизнеса в Таразе',
    metaTitle: 'Мобильная визитка для бизнеса в Таразе — tapni.kz',
    metaDescription: 'tapni.kz — мобильные визитки для предпринимателей Тараза. Kaspi Pay, 2ГИС, WhatsApp. Создайте страницу бесплатно.',
    h1: 'Мобильная визитка для бизнеса в Таразе',
    subtitle: 'Создайте tapni.kz-страницу с Kaspi Pay и 2ГИС для вашего бизнеса в Таразе.',
    keywords: ['мобильная визитка тараз', 'taplink тараз', 'визитка для бизнеса тараз'],
    audience: 'Предприниматели Тараза',
    buttons: [
      { icon: '💬', label: 'WhatsApp' },
      { icon: '💳', label: 'Kaspi Pay' },
      { icon: '📍', label: '2ГИС Тараз' },
      { icon: '✈️', label: 'Telegram' },
    ],
    localBusiness: { city: 'Тараз', regionCode: 'KZ-ZHA', lat: 42.90072, lon: 71.36427 },
  },
]

export const NICHE_SLUGS = NICHE_PAGES.map((p) => p.slug)
