import type { IconType } from './supabase'
import { PLACEHOLDER_PREFIX } from './templates'

// Copy generated by /api/generate from a one-line business description.
// Six short fields — the words a page needs, not its structure. URLs are the
// one thing the owner already knows and a model cannot guess.
export type PageCopy = {
  title: string
  bio: string
  wa_button: string
  wa_preset_text: string
  kaspi_button: string
  offer_button: string
}

export const COPY_FIELDS = [
  'title', 'bio', 'wa_button', 'wa_preset_text', 'kaspi_button', 'offer_button',
] as const

// Per-field caps. title and bio land in profiles.business_name / profiles.bio;
// the button fields land in links.title, capped at 100 by the API.
export const COPY_LIMITS: Record<keyof PageCopy, number> = {
  title: 60,
  bio: 160,
  wa_button: 60,
  wa_preset_text: 200,
  kaspi_button: 60,
  offer_button: 60,
}

/** Digits only, KZ-normalised: 8·707… and 707… both become 7707…. */
export function toWaNumber(raw: string): string {
  const digits = raw.replace(/\D/g, '')
  if (!digits) return ''
  if (digits.length === 10 && digits.startsWith('7')) return `7${digits}`
  if (digits.length === 11 && digits.startsWith('8')) return `7${digits.slice(1)}`
  return digits
}

/**
 * The three buttons the copy describes, which is exactly the free tier's limit —
 * a generated page fits without anything being silently dropped.
 *
 * Only WhatsApp can be finished here: a phone number produces a working wa.me
 * link carrying the pre-written first message.
 *
 * Kaspi gets the same stub the templates use. The offer link gets none at all —
 * a price list or portfolio lives at an address only the owner knows, and there
 * is no host to guess. It is created empty so it waits in the dashboard; the
 * public page skips links with no destination, so nobody is handed a button
 * that cannot work.
 */
export function buildLinksFromCopy(
  copy: PageCopy,
  phone: string,
): { title: string; url: string; icon_type: IconType }[] {
  const wa = toWaNumber(phone)
  const waUrl = wa
    ? `https://wa.me/${wa}?text=${encodeURIComponent(copy.wa_preset_text)}`
    : `${PLACEHOLDER_PREFIX}https://wa.me/7`

  return [
    { title: copy.wa_button, url: waUrl, icon_type: 'whatsapp' },
    { title: copy.kaspi_button, url: `${PLACEHOLDER_PREFIX}https://pay.kaspi.kz/pay/`, icon_type: 'kaspi_pay' },
    { title: copy.offer_button, url: '', icon_type: 'link' },
  ]
}

/** Trim, clamp and reject anything that is not all six fields as non-empty strings. */
export function sanitizeCopy(input: unknown): PageCopy | null {
  if (!input || typeof input !== 'object') return null
  const raw = input as Record<string, unknown>
  const out = {} as PageCopy
  for (const field of COPY_FIELDS) {
    const value = raw[field]
    if (typeof value !== 'string') return null
    const trimmed = value.trim().slice(0, COPY_LIMITS[field])
    if (!trimmed) return null
    out[field] = trimmed
  }
  return out
}
